name: Ruby

permissions: {}

on:
  push:
    branches:
      - "**"

  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - "3.4.2"

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - uses: actions/setup-go@v5
        with:
          go-version-file: ext/cybernetic_ruby_on_goroutine/go.mod
      - name: Run the default task
        run: bundle exec rake

  super-linter:
    name: Super-Linter
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # for super-linter
      - name: Super-Linter
        uses: super-linter/super-linter@v7.3.0
        env:
          LINTER_RULES_PATH: /
          LOG_LEVEL: NOTICE
          VALIDATE_RUBY: false
          VALIDATE_GO_MODULES: false
          VALIDATE_CPP: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
