name: Ruby

permissions: {}

on:
  push:
    branches:
      - "**"

  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.4.2'

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run the default task
        run: bundle exec rake

  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # for super-linter
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Bundle
        run: bundle
      - name: Super-Linter
        uses: super-linter/super-linter@v7.3.0
        env:
          LINTER_RULES_PATH: /
          LOG_LEVEL: NOTICE
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
